version: "2"
checks:
  file-lines:
    enabled: false
plugins:
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - rubocop:disable
  flog:
    enabled: true
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
