---
sudo: required
language: ruby
cache: bundler

# necessary for docker to work
dist: trusty
services:
  - docker

bundler_args: --without integration tools

matrix:
  include:
  - rvm: 1.9.3
    gemfile: Gemfile
  - rvm: 2.0
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
    script: bundle exec rake test:docker config=test/integration/test-runner.yaml
