version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  winrm_user: test_user
  winrm_pass: Pass@word1

  matrix:
    - ruby_version: "21"
      train_target: winrm://test_user@localhost:5985

    - ruby_version: "21"
      train_ssl: true
      train_target: winrm://test_user@localhost:5986

clone_folder: c:\projects\train
clone_depth: 1

cache:
  - C:\Ruby21\bin\gem

install:
  - systeminfo
  - ps: net user /add $env:winrm_user $env:winrm_pass
  - ps: net localgroup administrators $env:winrm_user /add
  - ps: $env:winrm_cert = (New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\localmachine\my).Thumbprint
  - ps: winrm create winrm/config/Listener?Address=*+Transport=HTTPS "@{Hostname=`"localhost`";CertificateThumbprint=`"$($env:winrm_cert)`"}"
  - ps: winrm set winrm/config/client/auth '@{Basic="true"}'
  - ps: winrm set winrm/config/service/auth '@{Basic="true"}'
  - ps: winrm set winrm/config/service '@{AllowUnencrypted="true"}'
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - ps: Write-Host $env:PATH
  - gem install bundler --quiet --no-ri --no-rdoc
  - gem update --system 2.4.5
  - ruby --version
  - gem --version
  - bundler --version
  - ruby -r rubygems -e "p Gem.path"

build_script:
  - bundle install --without integration tools

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake test:winrm
